[package]
name = "buy-round"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
eventstore = "2.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "1.3.3"
lazy_static = "1.4.0"
